import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { getDataFromTree } from "@apollo/client/react/ssr";
import withApollo from '../lib/withApollo';
import { Query,useQuery } from "../generated.index";
import Link from 'next/link'
import { get } from 'lodash'
import OutlinedCard from '../components/card';

function Home() {
  const { data } = useQuery();

  const launches = get(data, "launchesPast", []) as Query['launches']

  return( 
    <div className={styles.container}>
      <Head>
        <title>SpaceX Missions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            Welcome to SpaceX
        </h1>

        <p className={styles.description}>
          Learn more about the SpaceX Missions
        </p>

        <div className={styles.grid}>
          {launches.map(launch => 
              <Link 
                href="/missions/[id]" as={`/missions/${launch.id}`}
                key={launch.id}>
                  <div>
                  <OutlinedCard 
                    mission_date={launch.launch_date_local} 
                    mission_name={launch.mission_name}
                    mission_site={launch.launch_site.site_name_long}
                    />
                  </div>
              </Link>
          )}
        </div>
      </main>
    </div>
  )
}





export default withApollo(Home, { getDataFromTree })